name: Consume assets
on:
  workflow_dispatch:
    inputs:
      parameter1:
        description: 'Description for parameter1'
        required: true
jobs:
    consume assets:
      runs-on: ventus
      steps:
          - name: consume asset
            uses: dsaltares/fetch-gh-release-asset@master
            with:
              repo: 'dsaltares/godot-wild-jam-18'
              version: 'tags/v0.0.1'
              file: 'plague-linux.zip'
              token: ${{ secrets.MY_PAT }}