name: Trigger gateway
on:
  workflow_dispatch:
jobs:
    consume assets:
      runs-on: ventus
      steps:
          uses: dsaltares/fetch-gh-release-asset@master
          with:
            repo: 'dsaltares/godot-wild-jam-18'
            version: 'tags/v0.0.1'
            file: 'plague-linux.zip'
            token: ${{ secrets.MY_PAT }}