name: Upload assets
on:
  release:
    types: [released]
jobs:
  upload_artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Create Empty File
        run: touch empty_file.txt
      - name: Create zip
        if: ${{ github.event_name == 'release' }}
        run: |
          zip -r artifacts.zip ./* -x '*.git*'
      - name: Upload  Release Asset
        uses: softprops/action-gh-release@v1
        with:
          files: |
            artifacts.zip
