name: Trigger gateway
on:
  release:
    types: [released]
jobs:
  upload_artifact:
      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          files: |
            artifacts.zip