name: Upload assets
on:
  release:
    types: [released]
jobs:
  upload_artifact:
    runs-on: linux
    steps:
      - name: Upload  Release Asset
        uses: softprops/action-gh-release@v1
        with:
          files: |
            artifacts.zip
