name: Upload Random Logs

on:
  workflow_dispatch:

jobs:
  upload_logs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create logs directory
      run: mkdir -p logs

    - name: Generate Random Logs (Empty File)
      run: echo "Hello, World!" > logs/random_logs.txt  # Replace "Hello, World!" with any desired content

    - name: Upload Logs as Artifact
      uses: actions/upload-artifact@v2
      with:
        name: random_logs
        path: logs/random_logs.txt
